#!/usr/bin/env python3
"""
HetEval-1024: 1024 heterogeneous prompts for large-batch EPLB roofline validation.

First 512 prompts: reused from HetEval-512 (HetEval-128 + mt_bench + mgsm + gsm8k).
Next 512 prompts: new diverse prompts covering science, history, coding, math,
creative writing, logic, and general knowledge to maintain routing heterogeneity.
"""

from test_heteval512 import PROMPTS as _PROMPTS_512

_PROMPTS_NEW = [
    "Explain the difference between nuclear fission and fusion, and why fusion is harder to achieve on Earth.",
    "Write a short story about a robot that discovers it can dream.",
    "What is the time complexity of merge sort? Explain why it is O(n log n) with a step-by-step example using the array [38, 27, 43, 3, 9, 82, 10].",
    "A store sells apples for $1.50 each and oranges for $2.00 each. If Maria buys 6 apples and 4 oranges, how much does she spend?",
    "Compare and contrast the French Revolution and the American Revolution in terms of causes, key events, and outcomes.",
    "Explain how a hash table works, including collision resolution strategies like chaining and open addressing.",
    "A farmer has 120 meters of fencing. He wants to enclose a rectangular area next to a river, so he only needs fencing on three sides. What dimensions maximize the area?",
    "Write a haiku about the ocean at sunset.",
    "Explain the greenhouse effect and how it relates to global warming. What are the main greenhouse gases?",
    "Implement a binary search algorithm in Python and analyze its time complexity.",
    "What are the three laws of thermodynamics? Give a practical example for each.",
    "A ball is thrown upward with an initial velocity of 20 m/s. Ignoring air resistance, how high does it go and how long until it returns to the ground?",
    "Explain the difference between supervised, unsupervised, and reinforcement learning with examples.",
    "Write a poem about the changing seasons from winter to spring.",
    "What is the P vs NP problem? Why is it important in computer science?",
    "Calculate the determinant of the matrix [[1,2,3],[4,5,6],[7,8,9]]. Show your work step by step.",
    "Describe the process of plate tectonics and how it leads to earthquakes and volcanic eruptions.",
    "Explain OAuth 2.0 authentication flow with the roles of client, resource server, and authorization server.",
    "A rectangular swimming pool is 25 meters long and 10 meters wide. If it is filled to a depth of 2 meters, how many liters of water does it contain?",
    "Write a persuasive essay arguing for or against universal basic income.",
    "What is CRISPR-Cas9? How does it work and what are its potential applications in medicine?",
    "Explain the difference between TCP and UDP with specific use cases for each protocol.",
    "If you flip a fair coin 10 times, what is the probability of getting exactly 6 heads?",
    "Describe the water cycle, including evaporation, condensation, precipitation, and collection.",
    "Write a function in JavaScript that checks if a string is a palindrome.",
    "Explain the concept of supply and demand with a real-world example of price elasticity.",
    "A train leaves Station A at 9:00 AM traveling at 60 mph. Another train leaves Station B at 10:00 AM traveling toward Station A at 80 mph. If the stations are 280 miles apart, at what time do the trains meet?",
    "What are the main differences between RNA and DNA? Include structure, function, and location in the cell.",
    "Design a database schema for a library management system with books, members, loans, and reservations.",
    "Explain the concept of recursion with the Tower of Hanoi problem. How many moves are needed for n disks?",
    "What causes tides? Explain the roles of the Moon and the Sun in tidal patterns.",
    "Write a Python class for a linked list with insert, delete, and search methods.",
    "Explain the Doppler effect and give examples in both sound and light.",
    "A company's revenue increased from $2 million to $2.5 million over one year. What is the percentage growth rate?",
    "Compare the philosophies of Plato and Aristotle on the nature of reality.",
    "Explain how SSL/TLS encryption works to secure web communications.",
    "Solve the system of equations: 2x + 3y = 12 and 4x - y = 5. Show your work.",
    "What is the significance of the Rosetta Stone in understanding ancient Egyptian hieroglyphics?",
    "Write a SQL query to find the top 5 customers by total purchase amount from an orders table.",
    "Explain the concept of entropy in information theory and how it relates to data compression.",
    "A cylindrical tank has a radius of 3 meters and a height of 5 meters. What is its volume?",
    "Describe the differences between classical and operant conditioning in psychology.",
    "What is a blockchain? Explain the concepts of mining, consensus, and immutability.",
    "Convert the decimal number 156 to binary. Show the division method step by step.",
    "Explain photovoltaic cells: how do solar panels convert sunlight into electricity?",
    "Write a recursive Python function to compute the factorial of a number n.",
    "What are the four fundamental forces of nature? Describe each briefly.",
    "A recipe calls for 2/3 cup of sugar. If you want to make 1.5 times the recipe, how much sugar do you need?",
    "Explain the significance of the Turing test in artificial intelligence.",
    "Describe how a combustion engine works in a car, covering the four-stroke cycle.",
    "What is the difference between a stack and a queue? Give real-world examples.",
    "Explain the process of mitosis and meiosis, including the key differences between them.",
    "Write a bash script that finds all files larger than 100MB in a given directory.",
    "What is inflation? How does a central bank use interest rates to control it?",
    "A ladder 10 meters long leans against a wall. The foot of the ladder is 6 meters from the wall. How high up the wall does the ladder reach?",
    "Explain the concept of natural selection and how it drives evolution.",
    "Write a Python function to find the longest common subsequence of two strings.",
    "What is the Heisenberg uncertainty principle? Explain its implications for quantum mechanics.",
    "Calculate the compound interest on $10,000 invested at 5% annual rate for 3 years, compounded annually.",
    "Describe the architecture of a convolutional neural network (CNN) and its applications.",
    "What caused World War I? List and explain at least four major contributing factors.",
    "Explain the difference between a process and a thread in operating systems.",
    "A car depreciates by 15% per year. If it was bought for $30,000, what is it worth after 3 years?",
    "What is the difference between a virus and a bacterium? How do antibiotics and antivirals differ?",
    "Write a Python function to implement a simple LRU cache using OrderedDict.",
    "Explain the concept of comparative advantage in international trade with an example.",
    "Solve: A boat travels 30 km upstream in 3 hours and returns downstream in 2 hours. What is the speed of the boat in still water and the speed of the current?",
    "Describe the layers of the Earth's atmosphere and the key characteristics of each.",
    "What is a RESTful API? Explain the HTTP methods GET, POST, PUT, DELETE with examples.",
    "Explain the Pythagorean theorem and prove it using the area method.",
    "What is the significance of the Magna Carta in the development of constitutional law?",
    "Write a function in Python to detect a cycle in a linked list using Floyd's algorithm.",
    "Explain the electromagnetic spectrum from radio waves to gamma rays, with applications for each.",
    "If a pizza has a diameter of 16 inches, what is its area? How many square inches per slice if cut into 8 equal slices?",
    "Compare and contrast capitalism, socialism, and communism as economic systems.",
    "Explain how a neural network learns through backpropagation with a simple example.",
    "What is the difference between aerobic and anaerobic respiration in cells?",
    "Write a Python script that reads a CSV file and calculates the mean, median, and mode of a numeric column.",
    "Explain the concept of big-O notation with examples of O(1), O(n), O(n^2), and O(log n) algorithms.",
    "A projectile is launched at 45 degrees with an initial velocity of 50 m/s. Calculate the maximum height and range.",
    "What are the SOLID principles in software engineering? Give an example for each.",
    "Explain how vaccines work, including the concepts of antigens, antibodies, and herd immunity.",
    "Write a Python generator function that yields the Fibonacci sequence.",
    "What is the significance of Schrödinger's cat thought experiment in quantum physics?",
    "Calculate the area under the curve y = x^2 from x = 0 to x = 3 using integration.",
    "Describe the process of osmosis and how it affects plant cells versus animal cells.",
    "Explain the Model-View-Controller (MVC) design pattern with a web application example.",
    "A clock shows 3:15. What is the angle between the hour hand and the minute hand?",
    "What is dark matter? What evidence supports its existence?",
    "Write a Python function to perform matrix multiplication without using numpy.",
    "Explain the carbon cycle and the role of human activities in disrupting it.",
    "What is the difference between a monolithic and microservices architecture? Give trade-offs.",
    "Solve: Three workers can complete a job in 12 days. How long would it take 4 workers to complete the same job?",
    "Explain how the human immune system responds to a pathogen, covering innate and adaptive immunity.",
    "Write a Python decorator that measures the execution time of a function.",
    "What is the trolley problem in ethics? Discuss utilitarian versus deontological perspectives.",
    "Calculate the standard deviation of the data set: 4, 8, 6, 5, 3, 2, 8, 9, 2, 5.",
    "Explain how GPS (Global Positioning System) works, including the role of satellites and trilateration.",
    "Write a Python function to check if a binary tree is balanced.",
    "What is cognitive dissonance? Give examples of how people reduce it.",
    "A circular garden has a circumference of 62.8 meters. What is its area?",
    "Explain the concept of containerization with Docker and how it differs from virtual machines.",
    "What is string theory? Why do physicists consider it as a potential theory of everything?",
    "Write a Python function to sort a dictionary by its values in descending order.",
    "Explain the process of protein synthesis, covering transcription and translation.",
    "What is the difference between symmetric and asymmetric encryption? Give use cases.",
    "A shop offers a 20% discount on a $80 jacket, then charges 8% sales tax on the discounted price. What is the final price?",
    "Describe the life cycle of a star, from nebula to either white dwarf, neutron star, or black hole.",
    "Write a Python implementation of Dijkstra's shortest path algorithm.",
    "What is the prisoner's dilemma in game theory? How does it apply to real-world situations?",
    "Calculate the derivative of f(x) = 3x^3 - 2x^2 + 5x - 7. Then find f'(2).",
    "Explain the difference between the stack and the heap in memory management.",
    "What were the causes and consequences of the Industrial Revolution?",
    "Write a Python script that implements a simple web scraper using requests and BeautifulSoup.",
    "Explain the concept of polymorphism in object-oriented programming with examples in Python.",
    "A box contains 5 red balls, 3 blue balls, and 2 green balls. What is the probability of drawing 2 red balls in a row without replacement?",
    "What is the difference between weather and climate? How do scientists study climate change?",
    "Implement a min-heap in Python with insert and extract_min operations.",
    "Explain the concept of opportunity cost in economics with a personal decision example.",
    "What is the Krebs cycle? Describe its role in cellular respiration.",
    "Write a Python function to find all permutations of a string.",
    "Explain the concept of logical fallacies and give examples of ad hominem, straw man, and appeal to authority.",
    "A cylindrical pipe has an outer diameter of 10 cm and an inner diameter of 8 cm. What is the cross-sectional area of the pipe material?",
    "What is quantum entanglement? How is it used in quantum computing and communication?",
    "Write a Python class implementing a graph with BFS and DFS traversal methods.",
    "Explain the concept of elasticity in physics: stress, strain, and Young's modulus.",
    "What are the main differences between prokaryotic and eukaryotic cells?",
    "Implement a trie data structure in Python with insert and search methods.",
    "Explain the concept of moral relativism versus moral absolutism with examples.",
    "A rectangular field has an area of 5000 square meters. If the length is twice the width, find the dimensions.",
    "What is the Doppler effect in astronomy? How is it used to determine if a star is moving toward or away from us?",
    "Write a Python function to merge two sorted arrays into one sorted array.",
    "Explain the concept of neuroplasticity and how the brain changes with learning.",
    "What is the difference between a compiler and an interpreter? Give examples of languages that use each.",
    "Calculate the present value of $5000 to be received in 5 years at a discount rate of 8%.",
    "Describe the causes, events, and aftermath of the Black Death in medieval Europe.",
    "Write a Python function to implement a bloom filter.",
    "Explain the double-slit experiment and what it reveals about the wave-particle duality of light.",
    "What is functional programming? Explain the concepts of pure functions, immutability, and higher-order functions.",
    "A boat can travel 20 km/h in still water. The river current is 4 km/h. How long does it take to travel 48 km upstream?",
    "Explain the concept of market failure and give examples of externalities, public goods, and monopolies.",
    "Write a Python script that implements the Caesar cipher for encryption and decryption.",
    "What is epigenetics? How can environmental factors affect gene expression without changing DNA?",
    "Explain the difference between horizontal and vertical scaling in system design.",
    "Solve: A triangle has sides of length 7, 24, and 25. Is it a right triangle? What is its area?",
    "What is the significance of the Standard Model in particle physics?",
    "Write a Python function to convert a Roman numeral string to an integer.",
    "Explain the concept of herd immunity and the threshold needed for common diseases.",
    "What are design patterns? Explain the Singleton, Factory, and Observer patterns with examples.",
    "Calculate the volume of a sphere with radius 5 cm. Express your answer in terms of pi and as a decimal.",
    "Describe the history of the Internet, from ARPANET to the modern World Wide Web.",
    "Write a Python function to find the shortest path in a maze represented as a 2D grid.",
    "Explain the concept of cognitive biases and describe confirmation bias, anchoring, and the availability heuristic.",
    "A 5% solution of salt weighs 200 grams. How much salt and how much water does it contain?",
    "What is the difference between correlation and causation? Give a famous example of a spurious correlation.",
    "Write a Python function to serialize and deserialize a binary tree.",
    "Explain the concept of GDP (Gross Domestic Product) and the differences between nominal and real GDP.",
    "What are the main types of chemical bonds? Explain ionic, covalent, and metallic bonding.",
    "Implement a concurrent producer-consumer pattern in Python using threading and a queue.",
    "A pendulum has a length of 1 meter. What is its period of oscillation on Earth?",
    "Explain the concept of the social contract theory as proposed by Hobbes, Locke, and Rousseau.",
    "Write a Python function that implements binary tree inorder, preorder, and postorder traversals.",
    "What is the difference between RAM and ROM? Explain the types of each.",
    "A bakery sells croissants for $3 each and muffins for $2 each. If they sold 150 items for $380 total, how many of each did they sell?",
    "Explain the process of nuclear fission in a nuclear power plant, including the role of control rods.",
    "Write a Python function to find the kth largest element in an unsorted array.",
    "What is the butterfly effect in chaos theory? How does it relate to weather prediction?",
    "Calculate the eigenvalues of the matrix [[4, 2], [1, 3]]. Show your work.",
    "Describe the structure and function of the human heart, including the four chambers and valves.",
    "Write a Python function to implement the quicksort algorithm.",
    "What is the tragedy of the commons? Give modern examples and potential solutions.",
    "A satellite orbits Earth at a height of 400 km. Calculate its orbital speed and period.",
    "Explain the ACID properties of database transactions with examples.",
    "What is the Sapir-Whorf hypothesis? How does language influence thought?",
    "Write a Python function to check if two strings are anagrams of each other.",
    "Explain how transistors work and their role in modern computer processors.",
    "A right circular cone has a height of 12 cm and a base radius of 5 cm. Find its volume and slant height.",
    "What is the difference between deductive and inductive reasoning? Give examples of each.",
    "Write a Python function to implement a basic calculator that handles +, -, *, / with proper operator precedence.",
    "Explain the Coriolis effect and how it influences weather patterns and ocean currents.",
    "What is the difference between a B-tree and a B+ tree? When is each preferred?",
    "A company has fixed costs of $50,000 and variable costs of $20 per unit. If each unit sells for $50, what is the break-even point?",
    "Explain the concept of wave-particle duality with examples from light and electrons.",
    "Write a Python function to detect if a string contains valid parentheses, brackets, and braces.",
    "What is the overview effect described by astronauts, and how does it influence their perspective?",
    "A rectangle is inscribed in a circle of radius 5. What dimensions maximize the area of the rectangle?",
    "Explain how mRNA vaccines work, comparing them to traditional vaccine approaches.",
    "Write a Python function to implement a simple spell checker using edit distance.",
    "What are the main causes of biodiversity loss? Describe habitat destruction, invasive species, and climate change impacts.",
    "Implement a rate limiter in Python using the token bucket algorithm.",
    "What is the Monty Hall problem? Explain why switching doors gives a 2/3 probability of winning.",
    "A tank fills in 6 hours with pipe A and empties in 8 hours with pipe B. If both are open, how long to fill the tank?",
    "Explain the difference between deep learning and traditional machine learning approaches.",
    "Write a Python function to convert an infix expression to postfix notation.",
    "What is the historical significance of the Silk Road for trade and cultural exchange?",
    "Calculate the Taylor series expansion of e^x around x=0, up to the first 5 terms.",
    "Explain the concept of deadlock in operating systems and the four necessary conditions.",
    "What is the photoelectric effect? How did Einstein's explanation contribute to quantum theory?",
    "Write a Python function to find all prime factors of a given number.",
    "Describe the structure and function of DNA, including base pairing rules and the double helix.",
    "What is eventual consistency in distributed systems? Compare it with strong consistency.",
    "A regular hexagon has a side length of 6 cm. Calculate its area.",
    "Explain the concept of game theory and its applications in economics, politics, and biology.",
    "Write a Python function to implement a simple key-value store with expiration times.",
    "What is the difference between type I and type II errors in hypothesis testing?",
    "Explain how fiber optic communication works, including total internal reflection.",
    "A store marks up products by 40% over cost. If the selling price is $84, what was the cost?",
    "Describe the major philosophical schools of ancient Greece: Stoicism, Epicureanism, and Skepticism.",
    "Write a Python function to find the median of two sorted arrays in O(log(m+n)) time.",
    "Explain the concept of half-life in radioactive decay and calculate how much of a 100g sample remains after 3 half-lives.",
    "What is the CAP theorem? Give examples of databases that prioritize different combinations.",
    "A boat takes 2 hours to cross a 10 km wide lake. If the current pushes it 3 km downstream, what is the boat's actual speed?",
    "Explain the importance of the Higgs boson discovery at CERN in 2012.",
    "Write a Python class for a priority queue using a heap.",
    "What are the differences between classical mechanics, quantum mechanics, and relativistic mechanics?",
    "Calculate the sum of the infinite geometric series: 1 + 1/2 + 1/4 + 1/8 + ...",
    "Explain the concept of DevOps and the CI/CD pipeline with specific tools.",
    "What is Maslow's hierarchy of needs? Describe each level with examples.",
    "Write a Python function to rotate a matrix 90 degrees clockwise in-place.",
    "Explain how batteries work, comparing lithium-ion and lead-acid technologies.",
    "A gardener wants to create a circular flower bed with an area of 50 square meters. What should the radius be?",
    "Describe the process of fermentation and its applications in food and beverage production.",
    "Write a Python function to implement run-length encoding and decoding.",
    "Explain the concept of cognitive load theory and its implications for instructional design.",
    "What is the difference between a parametric and non-parametric statistical test?",
    "A 2 kg block slides down a frictionless inclined plane that makes a 30-degree angle with the horizontal. What is its acceleration?",
    "Explain the architecture of a transformer model, focusing on self-attention and positional encoding.",
    "Write a Python function to solve the N-Queens problem using backtracking.",
    "What are the causes and effects of ocean acidification?",
    "Describe the differences between IPv4 and IPv6, including address format and key improvements.",
    "A and B can complete a job in 12 days, B and C in 15 days, and A and C in 20 days. How long for all three together?",
    "Explain the concept of moral hazard in economics and insurance.",
    "Write a Python function to implement a simple hash map with separate chaining.",
    "What is the multiverse theory? What scientific evidence, if any, supports it?",
    "Calculate the integral of sin(x)*cos(x) dx. Show two different methods.",
    "Explain the concept of cache coherence in multi-processor systems.",
    "What is the overview of Maslow's hierarchy? List all five levels from bottom to top with examples.",
    "Write a Python function to find the longest palindromic substring in a string.",
    "Explain Ohm's law and Kirchhoff's laws with a practical circuit example.",
    "A loan of $20,000 at 6% annual interest is to be paid in 5 equal annual installments. What is the annual payment?",
    "Describe the causes and key events of the Cold War between the US and the Soviet Union.",
    "Write a Python function to implement topological sort for a directed acyclic graph.",
    "Explain the concept of entropy in thermodynamics and how it relates to the arrow of time.",
    "What is the difference between a relational database and a NoSQL database? Give use cases.",
    "A mixtures problem: How many liters of a 30% acid solution must be mixed with 10 liters of a 10% acid solution to get a 20% solution?",
    "Explain how nuclear magnetic resonance (NMR) works and its applications in MRI imaging.",
    "Write a Python function to generate all valid combinations of n pairs of parentheses.",
    "Describe the key features of Renaissance art and name three famous Renaissance artists.",
    "Describe the principles of aerodynamics: lift, drag, thrust, and weight.",
    "Write a Python function to find the maximum subarray sum using Kadane's algorithm.",
    "Explain the concept of diminishing marginal returns with a farming example.",
    "What are the main components of the endocrine system? Describe the function of three major glands.",
    "Implement a simple regular expression matcher in Python that supports '.' and '*'.",
    "A ball bounces to 3/4 of its previous height each time. If dropped from 16 meters, what total distance does it travel before stopping?",
    "Explain the concept of the observer effect in quantum mechanics.",
    "Write a Python function to count the number of islands in a 2D binary grid.",
    "What is the Pareto principle (80/20 rule)? Give examples from business and daily life.",
    "Calculate the work done in pushing a 50 kg crate 10 meters along a horizontal surface with a coefficient of friction of 0.3.",
    "Explain the difference between threads and coroutines in concurrent programming.",
    "A wire of length 100 cm is to be cut into two pieces. One piece forms a circle and the other a square. How should it be cut to minimize the total area?",
    "Describe the history of human rights, from natural rights theory to the Universal Declaration of Human Rights.",
    "Write a Python function to implement a simple text search using the KMP algorithm.",
    "What is CRISPR and how might it be used to treat genetic diseases in the future?",
    "Explain the concept of amortized analysis in algorithm design with the dynamic array example.",
    "A satellite dish has a parabolic cross-section. If it is 4 meters wide and 1 meter deep, where should the receiver be placed?",
    "What are the primary differences between HTTP/1.1, HTTP/2, and HTTP/3?",
    "Write a Python function to find the lowest common ancestor in a binary search tree.",
    "Explain the concept of the tragedy of the anticommons with examples.",
    "Calculate the moment of inertia of a solid cylinder about its central axis.",
    "Describe how superconductors work and their potential applications in technology.",
    "Write a Python function to implement a simple autocomplete system using a trie.",
    "What is behavioral economics? Explain loss aversion, framing effects, and nudge theory.",
    "A hemispherical bowl has a radius of 10 cm. Calculate its volume and surface area.",
    "Explain the concept of separation of concerns in software architecture.",
    "What are Van der Waals forces? How do they differ from hydrogen bonds?",
    "Write a Python function to convert a sorted array to a balanced binary search tree.",
    "Explain the concept of cultural hegemony as proposed by Antonio Gramsci.",
    "A capacitor of 10 microfarads is charged to 100 volts. Calculate the energy stored.",
    "Describe the main features and improvements of Python 3 over Python 2.",
    "Write a Python function to solve the coin change problem using dynamic programming.",
    "Explain Bayes' theorem with an example of medical diagnostic testing.",
    "What is the Chandrasekhar limit and why is it important for understanding white dwarfs?",
    "Implement a simple event-driven architecture in Python using callbacks.",
    "A parachutist jumps from a plane. Explain the physics of terminal velocity.",
    "What are the key differences between agile and waterfall project management methodologies?",
    "Write a Python function to implement the Rabin-Karp string matching algorithm.",
    "Explain the concept of the Nash equilibrium in game theory with a simple example.",
    "Calculate the electric field at a point 2 meters from a point charge of 5 microcoulombs.",
    "Describe the process of speciation and give an example of allopatric speciation.",
    "Write a Python function to find the diameter of a binary tree.",
    "What is the difference between fiscal policy and monetary policy?",
    "A lens has a focal length of 20 cm. An object is placed 30 cm from the lens. Where is the image formed?",
    "Explain the principles of cryptographic hashing and how SHA-256 is used in Bitcoin.",
    "Write a Python function to implement reservoir sampling for randomly selecting k items from a stream.",
    "What is the Fermi paradox? Discuss possible explanations for the apparent absence of extraterrestrial civilizations.",
    "Calculate the pH of a 0.01 M HCl solution. Is it acidic, neutral, or basic?",
    "Explain the concept of dependency injection and how it improves code testability.",
    "A right triangle has legs of 5 and 12. Find the hypotenuse, area, and the three angles.",
    "Describe the key events and significance of the Renaissance period in European history.",
    "Write a Python function to implement a simple skip list data structure.",
    "Explain the concept of entropy in machine learning decision trees.",
    "What is the difference between a monocot and a dicot plant? Give three distinguishing features.",
    "Implement a thread-safe singleton pattern in Python.",
    "A flywheel rotates at 300 rpm. If it decelerates at 5 rad/s^2, how long until it stops?",
    "Explain the concept of social constructivism in education theory.",
    "Write a Python function to compute the convex hull of a set of 2D points.",
    "What is dark energy? How does it relate to the accelerating expansion of the universe?",
    "Calculate the Fourier transform of a rectangular pulse. Explain the sinc function result.",
    "Describe the history and impact of the printing press on society and knowledge dissemination.",
    "Write a Python function to implement a least recently used (LRU) cache from scratch.",
    "Explain the concept of the efficient market hypothesis and its three forms.",
    "A spring has a spring constant of 200 N/m. How much work is needed to compress it by 0.1 m?",
    "What is the difference between a left join, right join, inner join, and full outer join in SQL?",
    "Write a Python function to find all strongly connected components in a directed graph.",
    "Explain the concept of confirmation bias and how it affects scientific research.",
    "What is the twin paradox in special relativity? How is it resolved?",
    "Implement a simple memory allocator in Python that supports malloc and free operations.",
    "Describe the main differences between Sunni and Shia Islam.",
    "Write a Python function to implement the A* search algorithm for pathfinding.",
    "Explain the physics of how an airplane generates lift using Bernoulli's principle.",
    "Calculate the expected value and variance of rolling two fair six-sided dice.",
    "Explain the difference between a mutex and a semaphore in concurrent programming.",
    "What are the main causes of the French Revolution? Describe the role of the Estates-General.",
    "Write a Python function to flatten a nested list of arbitrary depth.",
    "Explain the difference between endothermic and exothermic reactions with examples.",
    "A cone has a volume of 150 cubic cm and a height of 10 cm. What is its base radius?",
    "What is the significance of the Gutenberg printing press for European literacy?",
    "Write a Python function to implement a circular buffer with fixed capacity.",
    "Explain how noise-canceling headphones work using destructive interference.",
    "What is the difference between a greedy algorithm and dynamic programming? Give examples.",
    "A person invests $1000 at 4% compounded quarterly. What is the value after 2 years?",
    "Describe the process of glaciation and its effects on landscape formation.",
    "Write a Python function to check if a number is a power of two without using loops.",
    "Explain the concept of bounded rationality in behavioral economics.",
    "What is the Stefan-Boltzmann law? How does it relate to stellar luminosity?",
    "Implement a thread pool in Python using concurrent.futures.",
    "A wire carries a current of 5 amps. Calculate the magnetic field 0.1 m from the wire.",
    "Explain the difference between first-order and second-order logic.",
    "Write a Python function to rotate an array by k positions to the right.",
    "What is the importance of the Krebs cycle in cellular energy production?",
    "Describe the architecture of the TCP/IP protocol stack with all four layers.",
    "A car accelerates from 0 to 100 km/h in 8 seconds. What is its acceleration in m/s^2?",
    "Explain the concept of the tragedy of the commons with a modern environmental example.",
    "Write a Python function to find the minimum spanning tree using Kruskal's algorithm.",
    "What are the main types of renewable energy? Compare solar, wind, and hydroelectric.",
    "A trapezoid has parallel sides of 8 and 12 cm and a height of 5 cm. Find its area.",
    "Explain the difference between categorical and continuous variables in statistics.",
    "Write a Python function to implement a simple expression parser using recursive descent.",
    "What is the Dunning-Kruger effect? How does it manifest in everyday life?",
    "Calculate the centripetal acceleration of a car going around a 50 m radius turn at 20 m/s.",
    "Describe the main events and significance of the Civil Rights Movement in the US.",
    "Write a Python function to convert between different temperature scales (C, F, K).",
    "Explain how semiconductors work and their role in diodes and transistors.",
    "What is the difference between normalization and denormalization in database design?",
    "A projectile is launched at 60 degrees with velocity 40 m/s. Find the range and max height.",
    "Explain the concept of the social contract as described by John Locke.",
    "Write a Python function to implement binary search on a rotated sorted array.",
    "What are amino acids? How do they combine to form proteins?",
    "Describe the major differences between procedural and object-oriented programming.",
    "A triangle has vertices at (0,0), (6,0), and (3,4). Find its area using the coordinate method.",
    "Explain how a refrigerator works using the principles of thermodynamics.",
    "Write a Python function to find the longest increasing subsequence in an array.",
    "What is the overview of Bloom's taxonomy? List all six levels with examples.",
    "Calculate the resistance of a wire that is 2 meters long with a cross-section of 1 mm^2 and resistivity of 1.7e-8 ohm-m.",
    "Explain the difference between a primary key, foreign key, and composite key in databases.",
    "Write a Python function to implement the Fisher-Yates shuffle algorithm.",
    "What were the main causes of the fall of the Roman Empire?",
    "A pendulum clock gains 5 minutes per day. By what fraction should the pendulum length be changed?",
    "Explain the concept of the invisible hand in Adam Smith's economics.",
    "Write a Python function to compress a string using run-length encoding.",
    "What is the Anthropic principle? Discuss the weak and strong versions.",
    "Describe the process of cellular respiration and how it produces ATP.",
    "Write a Python function to merge k sorted linked lists.",
    "Explain the difference between potential energy and kinetic energy with examples.",
    "What is the significance of the Rosetta mission for understanding comets?",
    "Implement a basic observer pattern in Python for an event system.",
    "A cone is cut by a plane parallel to its base at half the height. What fraction of the volume is the smaller piece?",
    "Explain the concept of market equilibrium and how price is determined.",
    "Write a Python function to implement a basic version of the map-reduce pattern.",
    "What are the causes and effects of El Niño and La Niña weather patterns?",
    "Describe the architecture of a RISC processor versus a CISC processor.",
    "A 100 W light bulb is left on for 8 hours. How much energy does it consume in kWh?",
    "Explain the concept of the categorical imperative in Kant's moral philosophy.",
    "Write a Python function to find the maximum profit from at most k stock transactions.",
    "What is the difference between a proton, neutron, and electron?",
    "Describe how a nuclear reactor controls the chain reaction using control rods.",
    "Write a Python function to implement a simple Markov chain text generator.",
    "Explain the three types of plate boundaries and the geological features associated with each.",
    "A 10 ohm and 15 ohm resistor are connected in parallel. What is the equivalent resistance?",
    "What is the Sapir-Whorf hypothesis? Does language determine thought or merely influence it?",
    "Write a Python function to implement bucket sort for floating-point numbers.",
    "Explain the concept of economic externalities with examples of positive and negative externalities.",
    "A regular pentagon has a side length of 8 cm. Calculate its area.",
    "Describe the main components and functions of the human nervous system.",
    "Write a Python function to implement the Euclidean algorithm for finding the GCD.",
    "What is the uncertainty principle? How does it limit the precision of simultaneous measurements?",
    "Explain the difference between a monorepo and polyrepo approach in software development.",
    "Calculate the moment of inertia of a thin rod about its center.",
    "Describe the process of photosynthesis in C3 and C4 plants.",
    "Write a Python function to find the maximum width of a binary tree at any level.",
    "Explain the main principles of Stoic philosophy and their relevance today.",
    "A 500 g ball moving at 4 m/s collides elastically with a stationary 300 g ball. Find the velocities after collision.",
    "What is containerization? Explain how Kubernetes orchestrates containers at scale.",
    "Write a Python function to implement Huffman encoding for text compression.",
    "Explain the difference between Type 1 and Type 2 diabetes.",
    "A satellite in geostationary orbit has a period of 24 hours. Calculate its orbital radius.",
    "Describe the main events of the Space Race between the US and the Soviet Union.",
    "Write a Python function to solve the 0/1 knapsack problem using dynamic programming.",
    "Explain the concept of the time value of money and how it relates to discounted cash flow.",
    "What is the difference between mitosis and meiosis? Create a comparison table.",
    "Implement a simple publish-subscribe messaging system in Python.",
    "A prism with a triangular cross-section has sides 3, 4, 5 cm and length 10 cm. Find its volume.",
    "Explain the concept of opportunity cost with a business decision example.",
    "Write a Python function to implement a basic neural network perceptron from scratch.",
    "What were the major achievements of ancient Roman engineering?",
    "Calculate the escape velocity from the surface of Mars.",
    "Describe the role of the United Nations in maintaining international peace and security.",
    "Write a Python function to implement the Sieve of Eratosthenes for finding prime numbers.",
    "Explain the difference between weather fronts: cold front, warm front, occluded front, and stationary front.",
    "A ball is dropped from a height of 20 meters. How long does it take to reach the ground?",
    "What is the significance of the Hubble Space Telescope for astronomy?",
    "Write a Python function to implement a simple recommendation system using collaborative filtering.",
    "Explain the concept of diminishing marginal utility with a practical example.",
    "What is the difference between synchronous and asynchronous I/O in programming?",
    "A rectangular box has dimensions 3x4x5 cm. Find the length of its space diagonal.",
    "Describe the process of democratic governance, including the separation of powers.",
    "Write a Python function to implement a weighted random selection algorithm.",
    "Explain the concept of the electromagnetic induction and Faraday's law.",
    "What is the difference between machine learning classification and regression? Give examples.",
    "A ship travels 100 km east, then 80 km north. What is its displacement from the starting point?",
    "Explain the main differences between classical and quantum computing.",
    "Write a Python function to implement depth-limited search for a graph.",
    "What is the greenhouse effect? Compare natural vs enhanced greenhouse effect.",
    "Describe the Industrial Revolution's impact on urbanization and social classes.",
    "Write a Python function to convert a decimal number to any base (2-16).",
    "Explain the concept of elasticity of demand and its determinants.",
    "A pulley system has a mechanical advantage of 4. What force is needed to lift a 200 N object?",
    "What is the difference between empathy and sympathy? Give examples in a healthcare context.",
    "Write a Python function to find all bridges in an undirected graph.",
    "Explain the law of conservation of energy with three different physical scenarios.",
    "What are the major differences between prokaryotic and eukaryotic gene expression?",
    "Implement a simple state machine in Python for a traffic light controller.",
    "A cylinder rolls without slipping down an incline of 30 degrees. Find its acceleration.",
    "Explain the concept of recursion versus iteration in algorithm design.",
    "Write a Python function to perform polynomial multiplication using FFT.",
    "What is the significance of the discovery of the cosmic microwave background radiation?",
    "Describe the main approaches to garbage collection in programming languages.",
    "A 2 meter long uniform rod weighing 10 N is supported at its ends. What is the reaction at each support?",
    "Explain the difference between socialism and social democracy.",
    "Write a Python function to implement a simple HTTP server that handles GET and POST requests.",
    "What is the Higgs mechanism and why is the Higgs boson called the 'God particle'?",
    "Calculate the surface area of a torus with inner radius 2 and outer radius 5.",
    "Describe the major achievements and contributions of the Islamic Golden Age to science.",
    "Write a Python function to find the number of ways to climb n stairs taking 1 or 2 steps at a time.",
    "Explain the concept of hedge funds and how they differ from mutual funds.",
    "A convex lens has focal length 15 cm. Find the image position for an object at 20 cm.",
    "What is the significance of the Voyager missions for space exploration?",
    "Write a Python function to implement a simple garbage collector using reference counting.",
    "Explain the concept of natural monopoly and why utilities are often regulated.",
    "Describe the main features of Gothic architecture with examples of famous buildings.",
    "Write a Python function to detect palindromic substrings in a string using Manacher's algorithm.",
    "What is the overview of Bloom's taxonomy? List all six cognitive levels with example verbs.",
    "A solenoid has 1000 turns, length 0.5 m, and carries 2 A. Calculate the magnetic field inside.",
    "Explain the concept of moral luck in philosophy with examples.",
    "Write a Python function to implement a simple text tokenizer for NLP.",
    "What are the main differences between analog and digital signals?",
    "Describe the impact of the printing press on the Protestant Reformation.",
    "A flywheel starts from rest and reaches 600 rpm in 10 seconds. Calculate the angular acceleration.",
    "Explain the theory of multiple intelligences proposed by Howard Gardner.",
    "Write a Python function to solve a Sudoku puzzle using backtracking.",
    "What is the difference between heat and temperature? Explain with examples.",
    "Describe the history and significance of the Olympic Games, from ancient Greece to modern times.",
    "Write a Python function to implement a basic database query executor for SELECT statements.",
    "Explain the concept of heuristic search in AI with A* as an example.",
    "A wire loop of area 0.1 m^2 rotates in a 0.5 T magnetic field. What is the maximum EMF if it rotates at 50 Hz?",
    "What is the importance of biodiversity for ecosystem stability?",
    "Write a Python function to implement word2vec skip-gram model conceptually.",
    "Explain the different types of market structures: perfect competition, monopoly, oligopoly, and monopolistic competition.",
    "A water tank in the shape of an inverted cone has height 10 m and radius 5 m. If water flows in at 2 cubic meters per minute, how fast is the water level rising when the depth is 4 m?",
    "Explain the difference between latent heat and sensible heat with phase-change examples.",
    "Write a Python function to check if a graph is bipartite using BFS.",
    "What is the significance of the discovery of penicillin for modern medicine?",
    "Describe the main challenges of building a space elevator and proposed materials.",
    "A coin is biased with P(heads)=0.6. What is the probability of getting at least 2 heads in 3 flips?",
    "Explain the concept of the tragedy of the commons applied to overfishing.",
    "Write a Python function to compute the edit distance between two strings using DP.",
    "What are the main differences between liberalism and conservatism as political ideologies?",
    "A hollow sphere has inner radius 3 cm and outer radius 5 cm. What is its volume?",
    "Explain the process of gel electrophoresis and its applications in genetics.",
    "Write a Python function to implement a simple load balancer using round-robin scheduling.",
    "What is the significance of Mendel's laws of inheritance for genetics?",
    "Describe the difference between a monolithic kernel and a microkernel in OS design.",
    "A car travels 1/3 of a distance at 40 km/h, 1/3 at 50 km/h, and 1/3 at 60 km/h. What is the average speed?",
    "Explain the concept of the free rider problem in public goods economics.",
    "Write a Python function to find the median of a data stream in O(log n) time.",
    "What are the key events that led to the unification of Germany in 1871?",
    "Describe the difference between a bridge, switch, and router in computer networking.",
    "A satellite transmits at a frequency of 12 GHz. What is the wavelength of the signal?",
    "Explain the concept of the Phillips curve and its relationship between inflation and unemployment.",
    "Write a Python function to implement a simple blockchain with proof of work.",
    "What is the role of mitochondria in cellular respiration and why are they called the powerhouse of the cell?",
    "Describe the history of artificial neural networks from the perceptron to modern deep learning.",
    "A 20 kg box rests on an incline of 35 degrees. Calculate the normal force and the force of friction needed to keep it stationary.",
    "Explain the difference between common law and civil law legal systems.",
    "Write a Python function to implement gradient descent for linear regression.",
    "What is the Drake equation? Discuss the factors and their uncertainties.",
    "Describe the main steps in the scientific method with a concrete example.",
    "A series RLC circuit has R=10 ohm, L=0.1 H, C=100 microfarads. Find the resonant frequency.",
    "Explain the concept of comparative advantage with the example of two countries trading.",
    "Write a Python function to implement a simple decision tree classifier from scratch.",
    "What are prions? How do they cause disease without containing DNA or RNA?",
    "Explain the difference between parametric and non-parametric bootstrap methods in statistics.",
]

PROMPTS = list(_PROMPTS_512) + _PROMPTS_NEW

assert len(PROMPTS) >= 1024, f"Expected >= 1024 prompts, got {len(PROMPTS)}"

VERIFIABLE = {
    0: "average speed = 480/7 ~ 68.57 km/h",
    8: "x = 2 and x = 3",
    512 + 3: "$17.00",
    512 + 6: "width=30m, length=60m, max area=1800 sq m",
    512 + 22: "P(6 heads) = 210/1024 ~ 0.205",
}
