#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fig. 3 — Expert routing stability and concentration in dLLM block diffusion.

Panel (a): Pairwise Jaccard overlap heatmaps for Layer 4, 10, 18.
Panel (b): Expert routing concentration CDF (cumulative coverage).

Data source: codex_coding/results/plt/routing_stability_data.json
Generated by: codex_coding/src/collect_routing_stability.py
"""

import json
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from pathlib import Path


# =====================================================================
# Style
# =====================================================================

def apply_systems_style():
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans"],
        "mathtext.fontset": "dejavusans",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "font.size":        8.5,
        "axes.labelsize":   9.0,
        "axes.titlesize":   9.0,
        "axes.titleweight": "bold",
        "xtick.labelsize":  8.0,
        "ytick.labelsize":  8.0,
        "legend.fontsize":  8.0,
        "axes.linewidth":      0.7,
        "axes.edgecolor":      "#222222",
        "xtick.major.width":   0.7,
        "ytick.major.width":   0.7,
        "xtick.major.size":    2.8,
        "ytick.major.size":    2.8,
        "xtick.direction":     "in",
        "ytick.direction":     "in",
        "xtick.color":         "#222222",
        "ytick.color":         "#222222",
        "legend.frameon":         False,
        "legend.handlelength":    1.8,
        "legend.borderaxespad":   0.3,
        "legend.handletextpad":   0.5,
        "legend.columnspacing":   1.0,
        "hatch.linewidth": 0.5,
    })


C_NAVY   = "#1F3E6E"
C_RUST   = "#A6480F"
C_OLIVE  = "#3F6B30"
C_DARKG  = "#4A4A4A"
C_BLACK  = "#111111"

HEATMAP_CMAP = LinearSegmentedColormap.from_list(
    "epoch_systems_blues",
    [(0.00, "#FFFFFF"),
     (0.35, "#D6E0EE"),
     (0.70, "#6E8CB6"),
     (1.00, "#1F3E6E")]
)

DATA_PATH = Path(__file__).parent.parent.parent / "results" / "plt" / "routing_stability_data.json"


# =====================================================================
# Data loading
# =====================================================================

def load_data(path=None):
    if path is None:
        path = DATA_PATH
    with open(path) as f:
        raw = json.load(f)

    overlaps = {}
    layer_names = {"layer_4": "Layer 4", "layer_10": "Layer 10", "layer_18": "Layer 18"}
    for key, name in layer_names.items():
        overlaps[name] = np.array(raw["jaccard"][key]["jaccard_matrix"])

    cdfs = {}
    for key, name in layer_names.items():
        cdfs[name] = {
            "rank": np.array(raw["cdf"][key]["expert_rank"]),
            "pct":  np.array(raw["cdf"][key]["cumulative_pct"]),
        }

    meta = raw["meta"]
    return overlaps, cdfs, meta


# =====================================================================
# Fig. 3
# =====================================================================

def plot_fig3(out="fig3_routing_stability_compact", data_path=None):
    apply_systems_style()
    overlaps, cdfs, meta = load_data(data_path)

    fig = plt.figure(figsize=(5.0, 4.0))

    outer = fig.add_gridspec(
        nrows=2, ncols=1,
        height_ratios=[1.0, 0.80],
        hspace=0.45,
    )

    inner_top = outer[0].subgridspec(
        nrows=1, ncols=4,
        width_ratios=[1.0, 1.0, 1.0, 0.07],
        wspace=0.18,
    )

    ax_h1 = fig.add_subplot(inner_top[0, 0])
    ax_h2 = fig.add_subplot(inner_top[0, 1])
    ax_h3 = fig.add_subplot(inner_top[0, 2])
    cax   = fig.add_subplot(inner_top[0, 3])
    ax_b  = fig.add_subplot(outer[1])

    # ---------- (a) Heatmaps ----------
    heat_axes = [ax_h1, ax_h2, ax_h3]
    T = list(overlaps.values())[0].shape[0]

    tick_pos = [0, 6, 13, 20, T - 1]
    tick_lab = [str(i + 1) for i in tick_pos]

    vmin = 0.70

    im = None
    for i, (ax, (name, M)) in enumerate(zip(heat_axes, overlaps.items())):
        im = ax.imshow(
            M, vmin=vmin, vmax=1.0, cmap=HEATMAP_CMAP,
            origin="lower", interpolation="nearest", aspect="equal",
        )

        off_diag = M[np.triu_indices_from(M, k=1)]
        off_mean = off_diag.mean()
        ax.text(
            0.97, 0.04,
            f"$\\overline{{J}}$={off_mean:.2f}",
            transform=ax.transAxes, ha="right", va="bottom",
            fontsize=7.8, color=C_BLACK,
            bbox=dict(facecolor="white", edgecolor="#888", linewidth=0.5,
                      boxstyle="round,pad=0.18", alpha=0.95),
        )

        ax.set_xticks(tick_pos)
        ax.set_xticklabels(tick_lab)
        ax.set_yticks(tick_pos)
        if i == 0:
            ax.set_yticklabels(tick_lab)
            ax.set_ylabel("Iter. $i$", labelpad=1)
        else:
            ax.set_yticklabels([])
        ax.set_xlabel("Iter. $j$", labelpad=1)
        ax.tick_params(direction="out", length=2.2)
        ax.set_title(name, fontsize=8.5, fontweight="normal", pad=2)

    ax_h1.text(
        0.0, 1.18,
        "(a) Expert activation overlap is stable inside a block",
        transform=ax_h1.transAxes, ha="left", va="bottom",
        fontsize=9, fontweight="bold",
    )

    cbar = fig.colorbar(im, cax=cax)
    cbar.set_ticks([0.70, 0.80, 0.90, 1.00])
    cbar.ax.tick_params(labelsize=7.5, length=2.0, direction="in")
    cbar.outline.set_linewidth(0.6)
    cbar.set_label("Jaccard overlap", fontsize=8, labelpad=2)

    # ---------- (b) Routing Concentration CDF ----------
    line_styles = {
        "Layer 4":  {"color": C_NAVY,  "ls": "-",  "marker": "o"},
        "Layer 10": {"color": C_RUST,  "ls": "--", "marker": "s"},
        "Layer 18": {"color": C_OLIVE, "ls": "-.", "marker": "^"},
    }

    for name, cdf_data in cdfs.items():
        style = line_styles[name]
        rank = cdf_data["rank"]
        pct = cdf_data["pct"]
        step = max(1, len(rank) // 12)
        ax_b.plot(
            rank, pct,
            linestyle=style["ls"], linewidth=1.5, color=style["color"],
            marker=style["marker"], markersize=3.5,
            markevery=step, markerfacecolor="white", markeredgewidth=0.9,
            label=name, zorder=4,
        )

    ax_b.axhline(90, color=C_BLACK, linestyle=":", linewidth=0.7, alpha=0.5, zorder=2)
    ax_b.axhline(50, color=C_BLACK, linestyle=":", linewidth=0.5, alpha=0.4, zorder=2)

    l18_pct = cdfs["Layer 18"]["pct"]
    idx_90 = int(np.searchsorted(l18_pct, 90.0))
    ax_b.axvline(idx_90 + 1, color=C_BLACK, linestyle=":", linewidth=0.7, alpha=0.5, zorder=2)

    ax_b.annotate(
        f"Top {idx_90+1} experts\n({(idx_90+1)/256*100:.0f}%) cover 90%",
        xy=(idx_90 + 1, 90),
        xytext=(idx_90 + 45, 68),
        fontsize=7.8, ha="left", va="center", color=C_OLIVE, fontweight="bold",
        arrowprops=dict(arrowstyle="->", linewidth=0.7, color=C_OLIVE,
                        shrinkA=2, shrinkB=3),
        bbox=dict(facecolor="white", edgecolor="#888", linewidth=0.5,
                  boxstyle="round,pad=0.20", alpha=0.95),
    )

    l4_pct = cdfs["Layer 4"]["pct"]
    idx_50_l4 = int(np.searchsorted(l4_pct, 50.0))
    ax_b.annotate(
        f"Top {idx_50_l4+1} experts\ncover 50%",
        xy=(idx_50_l4 + 1, 50),
        xytext=(idx_50_l4 + 40, 32),
        fontsize=7.8, ha="left", va="center", color=C_NAVY,
        arrowprops=dict(arrowstyle="->", linewidth=0.7, color=C_NAVY,
                        shrinkA=2, shrinkB=3),
    )

    ax_b.set_xlim(0, 260)
    ax_b.set_ylim(0, 105)
    ax_b.set_xticks([1, 64, 128, 192, 256])
    ax_b.set_xlabel("Top-$K$ experts (sorted by token count, descending)", labelpad=2)
    ax_b.set_ylabel("Cumulative routing\ncoverage (%)", labelpad=2)
    ax_b.yaxis.grid(True, linestyle=":", linewidth=0.5, color="#999", alpha=0.7)
    ax_b.set_axisbelow(True)
    for s in ("top", "right"):
        ax_b.spines[s].set_visible(False)

    leg = ax_b.legend(loc="lower right", ncol=1, handlelength=2.4)
    for line in leg.get_lines():
        line.set_linewidth(1.4)

    ax_b.set_title(
        "(b) Expert routing is highly concentrated",
        loc="left", fontsize=9, fontweight="bold", pad=4,
    )

    fig.subplots_adjust(left=0.08, right=0.985, top=0.89, bottom=0.13)

    out_dir = Path(__file__).parent.parent.parent / "results" / "plt"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_stem = str(out_dir / out)
    fig.savefig(f"{out_stem}.pdf", bbox_inches="tight")
    fig.savefig(f"{out_stem}.png", dpi=320, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out_stem}.pdf / .png")


# =====================================================================
# Main
# =====================================================================

if __name__ == "__main__":
    import sys
    data_path = sys.argv[1] if len(sys.argv) > 1 else None
    plot_fig3(data_path=data_path)
