#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fig. 4 — MoE output stability: Decoded vs MASK tokens across datasets.

Box plot showing cosine similarity of routed expert outputs between
consecutive iterations, separated by token type.

Data source: codex_coding/results/plt/moe_output_stability_data.json
Generated by: codex_coding/src/collect_moe_output_stability.py
"""

import json
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# =====================================================================
# Style (shared with fig3.py)
# =====================================================================

def apply_systems_style():
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans"],
        "mathtext.fontset": "dejavusans",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "font.size":        8.5,
        "axes.labelsize":   9.0,
        "axes.titlesize":   9.0,
        "axes.titleweight": "bold",
        "xtick.labelsize":  8.0,
        "ytick.labelsize":  8.0,
        "legend.fontsize":  8.0,
        "axes.linewidth":      0.7,
        "axes.edgecolor":      "#222222",
        "xtick.major.width":   0.7,
        "ytick.major.width":   0.7,
        "xtick.major.size":    2.8,
        "ytick.major.size":    2.8,
        "xtick.direction":     "in",
        "ytick.direction":     "in",
        "xtick.color":         "#222222",
        "ytick.color":         "#222222",
        "legend.frameon":         False,
        "legend.handlelength":    1.8,
        "legend.borderaxespad":   0.3,
        "legend.handletextpad":   0.5,
        "legend.columnspacing":   1.0,
    })


C_NAVY   = "#1F3E6E"
C_RUST   = "#A6480F"
C_BLACK  = "#111111"
C_NAVY_L = "#A3B8D8"
C_RUST_L = "#E8C4A8"

DATA_PATH = (Path(__file__).parent.parent.parent
             / "results" / "plt" / "moe_output_stability_data.json")

SAMPLE_N = 1000


# =====================================================================
# Data loading
# =====================================================================

def load_data(path=None, seed=42):
    if path is None:
        path = DATA_PATH
    with open(path) as f:
        raw = json.load(f)

    rng = np.random.default_rng(seed)
    datasets = {}
    for ds_name, ds_data in raw["results"].items():
        dec = np.array(ds_data["decoded_sims"])
        mask = np.array(ds_data["mask_sims"])
        dec_sample = rng.choice(dec, size=min(SAMPLE_N, len(dec)), replace=False)
        mask_sample = rng.choice(mask, size=min(SAMPLE_N, len(mask)), replace=False)
        datasets[ds_name] = {
            "decoded": dec_sample,
            "mask": mask_sample,
            "stats": ds_data["stats"],
        }
    return datasets, raw["meta"]


# =====================================================================
# Fig. 4
# =====================================================================

def plot_fig4(out="fig4_moe_output_stability", data_path=None):
    apply_systems_style()
    datasets, meta = load_data(data_path)

    fig, ax = plt.subplots(figsize=(4.0, 3.0))

    ds_names = list(datasets.keys())
    n_ds = len(ds_names)
    group_width = 1.0
    box_width = 0.30
    gap = 0.08

    positions_dec = []
    positions_mask = []
    data_dec = []
    data_mask = []

    for i, ds_name in enumerate(ds_names):
        center = i * group_width
        positions_dec.append(center - (box_width / 2 + gap / 2))
        positions_mask.append(center + (box_width / 2 + gap / 2))
        data_dec.append(datasets[ds_name]["decoded"])
        data_mask.append(datasets[ds_name]["mask"])

    bp_dec = ax.boxplot(
        data_dec, positions=positions_dec, widths=box_width,
        patch_artist=True, showfliers=False, zorder=3,
        medianprops=dict(color="white", linewidth=1.2),
        whiskerprops=dict(color=C_NAVY, linewidth=0.8),
        capprops=dict(color=C_NAVY, linewidth=0.8),
        boxprops=dict(facecolor=C_NAVY_L, edgecolor=C_NAVY, linewidth=0.8),
    )
    for patch in bp_dec["boxes"]:
        patch.set_facecolor(C_NAVY_L)

    bp_mask = ax.boxplot(
        data_mask, positions=positions_mask, widths=box_width,
        patch_artist=True, showfliers=False, zorder=3,
        medianprops=dict(color="white", linewidth=1.2),
        whiskerprops=dict(color=C_RUST, linewidth=0.8),
        capprops=dict(color=C_RUST, linewidth=0.8),
        boxprops=dict(facecolor=C_RUST_L, edgecolor=C_RUST, linewidth=0.8),
    )
    for patch in bp_mask["boxes"]:
        patch.set_facecolor(C_RUST_L)

    # Jittered scatter overlay
    rng = np.random.default_rng(123)
    scatter_n = min(200, SAMPLE_N)
    for i in range(n_ds):
        dec_pts = rng.choice(data_dec[i], size=scatter_n, replace=False)
        jitter = rng.uniform(-box_width * 0.3, box_width * 0.3, size=scatter_n)
        ax.scatter(positions_dec[i] + jitter, dec_pts,
                   s=1.5, color=C_NAVY, alpha=0.25, zorder=2, rasterized=True)

        mask_pts = rng.choice(data_mask[i], size=scatter_n, replace=False)
        jitter = rng.uniform(-box_width * 0.3, box_width * 0.3, size=scatter_n)
        ax.scatter(positions_mask[i] + jitter, mask_pts,
                   s=1.5, color=C_RUST, alpha=0.25, zorder=2, rasterized=True)

    # Annotations: use mean for both decoded and mask
    for i in range(n_ds):
        st = datasets[ds_names[i]]["stats"]
        dec_label = f"{st['decoded']['mean']:.2f}"
        mask_label = f"{st['mask']['mean']:.2f}"
        ax.text(positions_dec[i], 1.0 + 0.03, dec_label,
                ha="center", va="bottom", fontsize=7.0, color=C_NAVY, fontweight="bold")
        ax.text(positions_mask[i], float(st['mask']['median']) - 0.05, mask_label,
                ha="center", va="top", fontsize=7.0, color=C_RUST, fontweight="bold")

    # Axes
    ax.set_xticks([i * group_width for i in range(n_ds)])
    ax.set_xticklabels(ds_names)
    ax.set_xlim(-0.6, (n_ds - 1) * group_width + 0.6)
    ax.set_ylim(-0.1, 1.15)
    ax.set_yticks([0.0, 0.25, 0.50, 0.75, 1.00])
    ax.set_ylabel("Cosine similarity\n(adjacent iterations)", labelpad=2)
    ax.yaxis.grid(True, linestyle=":", linewidth=0.5, color="#999", alpha=0.7)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)

    # Legend
    from matplotlib.patches import Patch
    legend_elements = [
        Patch(facecolor=C_NAVY_L, edgecolor=C_NAVY, linewidth=0.8, label="Decoded tokens"),
        Patch(facecolor=C_RUST_L, edgecolor=C_RUST, linewidth=0.8, label="MASK tokens"),
    ]
    ax.legend(handles=legend_elements, loc="lower right", ncol=1)

    ax.set_title(
        "Routed expert output stability: Decoded vs MASK",
        loc="left", fontsize=9, fontweight="bold", pad=4,
    )

    fig.subplots_adjust(left=0.15, right=0.97, top=0.88, bottom=0.12)

    out_dir = Path(__file__).parent.parent.parent / "results" / "plt"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_stem = str(out_dir / out)
    fig.savefig(f"{out_stem}.pdf", bbox_inches="tight")
    fig.savefig(f"{out_stem}.png", dpi=320, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out_stem}.pdf / .png")


if __name__ == "__main__":
    import sys
    data_path = sys.argv[1] if len(sys.argv) > 1 else None
    plot_fig4(data_path=data_path)
