#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fig. 5.2 — Practical cache quality per iteration step.

At each iteration within a block, shows the average cosine similarity
between cached and current MoE outputs across ALL decoded tokens.
This reflects the real cache accuracy during inference.

Data source: codex_coding/results/plt/cache_staleness_data.json
Generated by: codex_coding/src/collect_cache_staleness.py
"""

import json
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# =====================================================================
# Style (shared)
# =====================================================================

def apply_systems_style():
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans"],
        "mathtext.fontset": "dejavusans",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "font.size":        8.5,
        "axes.labelsize":   9.0,
        "axes.titlesize":   9.0,
        "axes.titleweight": "bold",
        "xtick.labelsize":  8.0,
        "ytick.labelsize":  8.0,
        "legend.fontsize":  8.0,
        "axes.linewidth":      0.7,
        "axes.edgecolor":      "#222222",
        "xtick.major.width":   0.7,
        "ytick.major.width":   0.7,
        "xtick.major.size":    2.8,
        "ytick.major.size":    2.8,
        "xtick.direction":     "in",
        "ytick.direction":     "in",
        "xtick.color":         "#222222",
        "ytick.color":         "#222222",
        "legend.frameon":         False,
        "legend.handlelength":    1.8,
        "legend.borderaxespad":   0.3,
        "legend.handletextpad":   0.5,
        "legend.columnspacing":   1.0,
    })


C_NAVY  = "#1F3E6E"
C_RUST  = "#A6480F"
C_OLIVE = "#3F6B30"
C_BLACK = "#111111"

DATA_PATH = (Path(__file__).parent.parent.parent
             / "results" / "plt" / "cache_staleness_data.json")


# =====================================================================
# Data loading
# =====================================================================

def load_data(path=None, max_step=28):
    if path is None:
        path = DATA_PATH
    with open(path) as f:
        raw = json.load(f)

    curves = {}
    for ds_name, ds_data in raw["datasets"].items():
        sr = ds_data["step_results"]
        steps = np.array(sr["steps"])
        mean = np.array(sr["mean"])
        std = np.array(sr["std"])
        n = np.array(sr["n"])
        mask = steps <= max_step
        curves[ds_name] = {
            "steps": steps[mask],
            "mean": mean[mask],
            "std": std[mask],
            "n": n[mask],
        }

    return curves, raw["meta"]


# =====================================================================
# Fig. 5.2
# =====================================================================

def plot_fig5_2(out="fig5_2_cache_quality_per_step", data_path=None):
    apply_systems_style()
    curves, meta = load_data(data_path)

    fig, ax = plt.subplots(figsize=(4.5, 2.8))

    line_styles = {
        "GSM8K":     {"color": C_NAVY,  "ls": "-",  "marker": "o"},
        "HumanEval": {"color": C_RUST,  "ls": "--", "marker": "s"},
        "MT-Bench":  {"color": C_OLIVE, "ls": "-.", "marker": "^"},
    }

    for ds_name, data in curves.items():
        style = line_styles[ds_name]
        steps = data["steps"]
        mean = data["mean"]
        std = data["std"]

        step = max(1, len(steps) // 10)
        ax.plot(
            steps, mean,
            linestyle=style["ls"], linewidth=1.5, color=style["color"],
            marker=style["marker"], markersize=3.5,
            markevery=step, markerfacecolor="white", markeredgewidth=0.9,
            label=ds_name, zorder=4,
        )
        ax.fill_between(
            steps, mean - 0.25 * std, mean + 0.25 * std,
            alpha=0.04, color=style["color"], zorder=2, linewidth=0,
        )

    # Quality threshold line
    ax.axhline(0.95, color=C_BLACK, linestyle="--", linewidth=0.8, alpha=0.4, zorder=3)
    ax.text(27, 0.943, "quality threshold = 0.95",
            fontsize=7.0, ha="right", va="top", color=C_BLACK, alpha=0.6)

    # M=5 annotation
    ax.axvline(5, color=C_BLACK, linestyle=":", linewidth=0.8, alpha=0.5, zorder=3)
    sims_5 = []
    for data in curves.values():
        idx = np.searchsorted(data["steps"], 5)
        if idx < len(data["mean"]):
            sims_5.append(data["mean"][idx])
    avg_sim_5 = np.mean(sims_5)
    ax.annotate(
        f"$M$=5 (avg={avg_sim_5:.2f})",
        xy=(5, avg_sim_5),
        xytext=(9, 1.00),
        fontsize=7.8, ha="left", va="top", color=C_BLACK,
        arrowprops=dict(arrowstyle="->", linewidth=0.6, color=C_BLACK,
                        shrinkA=2, shrinkB=3),
        bbox=dict(facecolor="white", edgecolor="#888", linewidth=0.5,
                  boxstyle="round,pad=0.18", alpha=0.95),
    )

    max_step = max(int(d["steps"][-1]) for d in curves.values())
    ax.set_xlim(0.5, min(max_step, 28) + 0.5)
    ax.set_ylim(0.70, 1.03)
    ax.set_xticks([1, 5, 10, 15, 20, 25])
    ax.set_xlabel("Iteration step (within block)", labelpad=2)
    ax.set_ylabel("Cosine similarity", labelpad=2)
    ax.yaxis.grid(True, linestyle=":", linewidth=0.5, color="#999", alpha=0.7)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)

    ax.legend(loc="upper right", ncol=1)

    ax.set_title(
        "Cache staleness",
        loc="center", fontsize=9, fontweight="bold", pad=4,
    )

    fig.subplots_adjust(left=0.15, right=0.97, top=0.87, bottom=0.16)

    out_dir = Path(__file__).parent.parent.parent / "results" / "plt"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_stem = str(out_dir / out)
    fig.savefig(f"{out_stem}.pdf", bbox_inches="tight")
    fig.savefig(f"{out_stem}.png", dpi=320, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out_stem}.pdf / .png")


if __name__ == "__main__":
    import sys
    data_path = sys.argv[1] if len(sys.argv) > 1 else None
    plot_fig5_2(data_path=data_path)
