#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Fig. 5 — Cache staleness decay: cosine similarity vs cache gap.

Shows how decoded token MoE output drifts from its cached baseline
(captured at t_decode+1) as more forwards pass within a block.
One curve per dataset, each pooled across Layer 4/10/18.

Data source: codex_coding/results/plt/cache_staleness_data.json
Generated by: codex_coding/src/collect_cache_staleness.py
"""

import json
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# =====================================================================
# Style (shared)
# =====================================================================

def apply_systems_style():
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["DejaVu Sans"],
        "mathtext.fontset": "dejavusans",
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
        "font.size":        8.5,
        "axes.labelsize":   9.0,
        "axes.titlesize":   9.0,
        "axes.titleweight": "bold",
        "xtick.labelsize":  8.0,
        "ytick.labelsize":  8.0,
        "legend.fontsize":  8.0,
        "axes.linewidth":      0.7,
        "axes.edgecolor":      "#222222",
        "xtick.major.width":   0.7,
        "ytick.major.width":   0.7,
        "xtick.major.size":    2.8,
        "ytick.major.size":    2.8,
        "xtick.direction":     "in",
        "ytick.direction":     "in",
        "xtick.color":         "#222222",
        "ytick.color":         "#222222",
        "legend.frameon":         False,
        "legend.handlelength":    1.8,
        "legend.borderaxespad":   0.3,
        "legend.handletextpad":   0.5,
        "legend.columnspacing":   1.0,
    })


C_NAVY  = "#1F3E6E"
C_RUST  = "#A6480F"
C_OLIVE = "#3F6B30"
C_BLACK = "#111111"

DATA_PATH = (Path(__file__).parent.parent.parent
             / "results" / "plt" / "cache_staleness_data.json")


# =====================================================================
# Data loading
# =====================================================================

def load_dataset_curve(ds_data, max_gap=20):
    """Pool across layers for one dataset, return (gaps, mean, std)."""
    layer_keys = [k for k in ds_data["results"] if k.startswith("layer_")]
    all_means, all_stds, all_ns = [], [], []
    gaps = None

    for key in layer_keys:
        r = ds_data["results"][key]
        g = np.array(r["gaps"])
        mask = g <= max_gap
        if gaps is None:
            gaps = g[mask]
        all_means.append(np.array(r["mean"])[mask])
        all_stds.append(np.array(r["std"])[mask])
        all_ns.append(np.array(r["n"])[mask])

    all_means = np.array(all_means)
    all_stds = np.array(all_stds)
    all_ns = np.array(all_ns)

    total_n = all_ns.sum(axis=0)
    pooled_mean = (all_ns * all_means).sum(axis=0) / total_n
    pooled_var = (all_ns * (all_stds ** 2 + (all_means - pooled_mean) ** 2)).sum(axis=0) / total_n
    pooled_std = np.sqrt(pooled_var)

    # Prepend gap=0 → sim=1.0
    gaps = np.concatenate([[0], gaps])
    pooled_mean = np.concatenate([[1.0], pooled_mean])
    pooled_std = np.concatenate([[0.0], pooled_std])

    return gaps, pooled_mean, pooled_std


def load_data(path=None):
    if path is None:
        path = DATA_PATH
    with open(path) as f:
        raw = json.load(f)

    curves = {}
    for ds_name, ds_data in raw["datasets"].items():
        gaps, mean, std = load_dataset_curve(ds_data)
        curves[ds_name] = {"gaps": gaps, "mean": mean, "std": std}

    return curves, raw["meta"]


# =====================================================================
# Fig. 5
# =====================================================================

def plot_fig5(out="fig5_cache_staleness_decay", data_path=None):
    apply_systems_style()
    curves, meta = load_data(data_path)

    fig, ax = plt.subplots(figsize=(4.5, 2.8))

    line_styles = {
        "GSM8K":     {"color": C_NAVY,  "ls": "-",  "marker": "o"},
        "HumanEval": {"color": C_RUST,  "ls": "--", "marker": "s"},
        "MT-Bench":  {"color": C_OLIVE, "ls": "-.", "marker": "^"},
    }

    for ds_name, data in curves.items():
        style = line_styles[ds_name]
        gaps = data["gaps"]
        mean = data["mean"]
        std = data["std"]

        step = max(1, len(gaps) // 10)
        ax.plot(
            gaps, mean,
            linestyle=style["ls"], linewidth=1.5, color=style["color"],
            marker=style["marker"], markersize=3.5,
            markevery=step, markerfacecolor="white", markeredgewidth=0.9,
            label=ds_name, zorder=4,
        )
        ax.fill_between(
            gaps, mean - 0.25 * std, mean + 0.25 * std,
            alpha=0.12, color=style["color"], zorder=2, linewidth=0,
        )

    # M=5 vertical reference
    ax.axvline(5, color=C_BLACK, linestyle=":", linewidth=0.8, alpha=0.5, zorder=3)

    # Average sim at M=5 across datasets
    sims_5 = []
    for data in curves.values():
        idx = np.searchsorted(data["gaps"], 5)
        if idx < len(data["mean"]):
            sims_5.append(data["mean"][idx])
    avg_sim_5 = np.mean(sims_5)

    ax.annotate(
        f"$M$=5 (avg={avg_sim_5:.2f})",
        xy=(5, avg_sim_5),
        xytext=(9, avg_sim_5 + 0.04),
        fontsize=7.8, ha="left", va="bottom", color=C_BLACK,
        arrowprops=dict(arrowstyle="->", linewidth=0.6, color=C_BLACK,
                        shrinkA=2, shrinkB=3),
        bbox=dict(facecolor="white", edgecolor="#888", linewidth=0.5,
                  boxstyle="round,pad=0.18", alpha=0.95),
    )

    max_gap = max(int(d["gaps"][-1]) for d in curves.values())
    ax.set_xlim(-0.3, min(max_gap, 20) + 0.5)
    ax.set_ylim(0.72, 1.03)
    ax.set_xticks([0, 5, 10, 15, 20])
    ax.set_xlabel("Cache gap (forwards since caching)", labelpad=2)
    ax.set_ylabel("Cosine similarity\n(cached vs current)", labelpad=2)
    ax.yaxis.grid(True, linestyle=":", linewidth=0.5, color="#999", alpha=0.7)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)

    ax.legend(loc="upper right", ncol=1)

    ax.set_title(
        "Cache staleness decay (decoded tokens)",
        loc="left", fontsize=9, fontweight="bold", pad=4,
    )

    fig.subplots_adjust(left=0.15, right=0.97, top=0.87, bottom=0.16)

    out_dir = Path(__file__).parent.parent.parent / "results" / "plt"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_stem = str(out_dir / out)
    fig.savefig(f"{out_stem}.pdf", bbox_inches="tight")
    fig.savefig(f"{out_stem}.png", dpi=320, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved {out_stem}.pdf / .png")


if __name__ == "__main__":
    import sys
    data_path = sys.argv[1] if len(sys.argv) > 1 else None
    plot_fig5(data_path=data_path)
